pub mod analytics;
pub mod backup;
pub mod clipboard;
pub mod collections;
pub mod database;
pub mod dedup;
pub mod error;
pub mod events;
pub mod games;
pub mod hardware;
pub mod health;
pub mod jsonbin;
pub mod known_issues;
pub mod launcher;
pub mod metadata;
pub mod ping;
pub mod playtime;
pub mod queue;
pub mod scanner;
pub mod sessions;
pub mod settings;
pub mod sources;
pub mod tags;
pub mod twitch;
pub mod utils;
pub mod version_check;
pub mod window;
pub mod wrapped;

#[cfg(test)]
mod tests;
